### ISSUE TITLE
Find out why it won't run on Raspbian.

### ISSUE THREAD

**Issue by bobbydilley** [bobbydilley/OpenJVS3#21]
The software doesn't work on Raspbian and gives the following results:

- New Engine (engine_megre): doesn't come up with a JVS IO at all.
- Old Engine (master): works in the system settings, but games crash when starting

It does run fine on Ubuntu, but this can only be installed on a Raspberry Pi2 and over. It would be nice to have it working with Debian. The operating systems are quite similar so not sure what the issue is, could be worth looking at:

- Process priority, does the process get a higher priority in ubuntu?
- USBSerial driver, is it using a different driver for some reason?

**Comment by GXTX** [comment]
Testing with the current `master` release on Raspbian on a 3B+ it works perfectly fine. In case it was something odd I still followed the guide for Ubuntu by running 
```
sudo groupadd -f --system gpio
sudo groupadd -f --system i2c
sudo groupadd -f --system input
sudo groupadd -f --system spi
```
This might not be needed.

**Comment by bobbydilley** [comment]
Have also tested and can see it works on raspian on Pi2.

Testing on Pi1 now...

**Comment by bobbydilley** [comment]
Works fine!
