### ISSUE TITLE
Broken Analog Scaling

### ISSUE THREAD

**Issue by GXTX** [bobbydilley/OpenJVS3#27]
I'm not sure I should even open this issue since things are getting changed quickly right now.

Analog scaling was broken in `4687d382` (according to blame), it was set to be an `int` instead of what should probably be a  `float` so it's currently either 0/1, it's also broken in other places because everything is expecting an `int` now.

**Comment by GXTX** [comment]
Fixed in cd69adc.

**Comment by bobbydilley** [comment]
Thank you so much - I tested last night without going through a full game play so didn't see that bug! I'm aiming to keep master working, so any issues you find on it please say!

Currently testing the fix now.

**Comment by bobbydilley** [comment]
Tested and fixed.
