### ISSUE TITLE
Add in an ability to reverse controls

### ISSUE THREAD

**Issue by bobbydilley** [bobbydilley/OpenJVS3#4]
Microsoft side winder wheels pedals go from fully un-pressed at 255 to pressed at 0.

Need to add a `REVERSE` flag at the end

**Comment by GXTX** [comment]
Added in 0ebe537?

**Comment by bobbydilley** [comment]
Can now use the keyword `REV_ABS` to reverse the values coming from the device.

Thanks again to GXTX for the reminder.
