### ISSUE TITLE
Add Sync line support (Raspi)

### ISSUE THREAD

**Issue by RedOne87** [bobbydilley/OpenJVS3#6]
Add sync line support when used on raspberry pi.
Support for sync line can be configured via a config file/cmd argument OR a compiler define

**Comment by bobbydilley** [comment]
Sync line support has been added in as a runtime variable.
Will be nice to add it to a config file

**Comment by GXTX** [comment]
I'm a little confused about sync line. JVS spec only has 3 pins with one of them only being used during the initial process of giving devices IDs (sense pin). Am I missing something?

**Comment by bobbydilley** [comment]
In the following I'm gonna use Naomi to mean the arcade system, so this could be Chihiro/Lindbergh/Ringedge etc.

For RS485 you've got Data+, Data- and GND. Data+ and Data- are just oposites of each other which allows you to have a super long length of cable.

The JVS spec adds in the red sync line which it uses for daisy chaining JVS IOs together. The Naomi sends 5v down the sync line. The JVS IO should initially pull this to 2.5 volts (I use a resistor ladder for this). The 2.5 volts indicates to the Naomi that an IO is plugged in. The Naomi then sends a SET_ADDRESS command to set that JVS IOs address, and once this has done the JVS IO should pull this to 0 volts (ground). This is what you do for just 1 JVS IO, i'm not sure quite how the daisy chaining actually works, but all we're really concerned about is pulling the line to 2.5v before initialisation and to 0v after.

You can download the spec here and translate it into english on google translate. It explains the setting procedure probably better than I do - http://superusr.free.fr/arcade/JVS/JVST_VER3.pdf

**Comment by GXTX** [comment]
Gotcha yeah so the sense line, the term "sync" made me think otherwise.

Unrelated to this issue but because you mention daisy chaining, I actually did try to daisy chain OpenJVS2 from a IO board, caused by Chihiro to report both had no name and no features but could see them attached (but I also have many other issues with v2 as I stated in my email). I wonder if it was just a case of OJVS replying when the 1st in the chain was meant to.

**Comment by bobbydilley** [comment]
You're right it is called the sense line, not the sync line - my mistake, I'll make sure it is sense in the code.

I think you mean OpenJVS3? It's not built for daisy chaining at the moment and so I don't suspect it'll work at all - haven't thought about that in terms of code wise, but if its something you think would be useful we could take a look later on. I was actually thinking about this today.

I've tested the latest version of OpenJVS (as of this evening's commit) on a Chihiro Type 3 with sense line and it's working fine for me - feel free to make an issue if your still having problems.

**Comment by GXTX** [comment]
No I meant the original project `bobbydilley/OpenJVS`. But I can confirm and just have tested this is working as expected. Chihiro is happy and no longer crashing on input test, still haven't figured out the actual input scheme but will eventually.

**Comment by RedOne87** [comment]
>  This is what you do for just 1 JVS IO, i'm not sure quite how the daisy chaining actually works, but all we're really concerned about is pulling the line to 2.5v before initialisation and to 0v after.

The daisy-chaining works like this:
Each node has two JVS connectors which I will call A and B here. A is the one in the direction of the JVS master and B down the chain. At the beginning when no node is addresse after power-up or reset every node will pull the sense line at A down to 2.5V (= Node that is not addressed). At B it will see the that the node down the chain is pulling the line to 2.5V and thus knows that there is a node down the chain. The last node in the chain will sense at B that there is nobody pulling down the 5V and thus knows that it's the last node. When the address sequence is started by the JVS master each node will ignore and forward this message as long it is NOT the last knode. When the last node gets this adressing message it will answer and pull down A to 0 V. The next node up the chain will sense this at it's B and knows that it's neighbor node is addresse and will answer the next address comannd... This happens until all nodes have an address.

The head of OpenJVS currently has a couple of debug lines that interfere with multiple IOs but in general it is possible to use OpenJVS as last node in a chain

**Comment by bobbydilley** [comment]
I've done tests before where I pull the sense line to 2.5v, and reply to a single CMD_SETADDRESS command. With the above logic, I should expect a second CMD_SETADDRESS command which I usually don't see?

I was going to suggest that we could have OpenJVS emulating 2 IO boards itself, as some games actually require this?
